Repository prgrms-fe-devcourse/FEDC5_DevNamu_eunsu, pull requests merged in 2023-12, with the labels that each got.

#4 [#1] React-router 및 React-query 초기 설정
  package.json
  src/App.tsx
  src/components/Layout/Sidebar.tsx
  src/components/Layout/index.tsx
  src/components/MyThreads/.empty
  src/pages/Home/.empty
  src/pages/Home/index.tsx
  src/pages/MyNotifications/.empty
  src/pages/MyNotifications/index.tsx
  src/pages/MyThreads/index.tsx
  src/pages/MyTreads/.empty
  src/pages/NotFound/index.tsx
  yarn.lock
Labels: ⚙ Chore

#7 [#2] Commitlint 팀 규칙에 맞게 설정
  .husky/commit-msg
  commitlint.config.cjs
  package.json
  yarn.lock
Labels: ⚙ Chore

#10 [#9] Chore: tailwind px to rem
  src/index.css
  tailwind.config.js
Labels: ⚙ Chore

#14 [#13] Chore: commit lint 오타 수정
  commitlint.config.cjs
Labels: ⚙ Chore

#12 [#3] Feat: axios core 추상화 구현 및 react query 예시 코드 구현
  package.json
  src/apis/.empty
  src/apis/channel/queryFn.ts
  src/apis/channel/queryKey.ts
  src/apis/channel/useChannelQuery.ts
  src/apis/core.ts
  src/utils/localStorage.ts
  yarn.lock
Labels: ✨ Feature

#20 [#19] Docs: pull request template 수정
  .github/pull_request_template.md
Labels: 📃 Docs

#11 [#8] Style: 사이드바 및 레이아웃 퍼블리싱
  index.html
  public/background-gradient.css
  src/components/Layout/Sidebar.tsx
  src/components/Layout/Sidebar/ThemeConfigDropdown.tsx
  src/components/Layout/Sidebar/config.ts
  src/components/Layout/Sidebar/index.tsx
  src/components/Layout/Sidebar/styles.ts
  src/components/Layout/Sidebar/view.tsx
  src/components/Layout/index.tsx
Labels: 🎨 Style
