Repository prgrms-fe-devcourse/FEDC5_DevNamu_eunsu, pull requests merged in 2024-01, with the labels that each got.

#27 [#26] Feat: axios interceptors를 사용하여 repsonse 가공
  src/apis/core.ts
Labels: ✨ Feature

#18 [#15] Feat: 홈 페이지의 채널 메뉴 UI 구현
  public/svg/home.svg
  src/App.tsx
  src/components/Home/.empty
  src/components/Home/ChannelNavigationMenu.tsx
  src/pages/Home/index.tsx
Labels: ✨ Feature

#23 [#22] Feat: 로그인, 회원가입 모달 퍼블리싱
  src/components/Layout/Modals/Base/form.tsx
  src/components/Layout/Modals/Base/modal.tsx
  src/components/Layout/Modals/Login/config.ts
  src/components/Layout/Modals/Login/index.tsx
  src/components/Layout/Modals/Register/config.ts
  src/components/Layout/Modals/Register/index.tsx
  src/components/Layout/Sidebar/view.tsx
  src/components/ui/form.tsx
Labels: 🎨 Style

#32 [#30] Feat: response types 선언
  src/types/channel.ts
  src/types/notification.ts
  src/types/thread.ts
  src/types/user.ts
Labels: ✨ Feature

#29 [#6] Feat: 멘션 추가 / 삭제 기능 구현과 예시 코드
  package.json
  src/App.tsx
  src/components/Common/Mention/AutoCompleteMentionList.tsx
  src/components/Common/Mention/MentionInput.tsx
  src/components/Common/Mention/UserBadgeList.tsx
  src/components/Demo/ExMentionInput.tsx
  src/constants/dummyData.ts
  src/lib/autoComplete.ts
  yarn.lock
Labels: ✨ Feature

#34 [#17] Feat: 로그인 로직 구현 및 api 연결
  src/apis/auth/queryFn.ts
  src/apis/auth/useLogin.ts
  src/components/Layout/Modals/Login/index.tsx
  src/stores/.empty
  src/stores/user.ts
Labels: ✨ Feature

#28 [#24] Feat: 내가 쓴 글 ui 구현
  src/components/MyThreads/ThreadBody.tsx
  src/components/MyThreads/ThreadHeader.tsx
  src/components/MyThreads/ThreadItem.tsx
  src/pages/MyThreads/index.tsx
Labels: ✨ Feature

#35 [#21] Feat: thread list UI 구현 및 데이터 패칭
  public/svg/userProfile.svg
  src/apis/channel/queryFn.ts
  src/apis/channel/queryKey.ts
  src/apis/channel/useChannelDetailsQuery.ts
  src/apis/thread/queryFn.ts
  src/apis/thread/queryKey.ts
  src/apis/thread/useThreadsQuery.ts
  src/components/Home/ChannelNavigationMenu.tsx
  src/components/Home/ThreadList.tsx
  src/hooks/api/useThreadsByChannel.ts
  src/pages/Home/index.tsx
  src/types/user.ts
  src/utils/ parsingJson.ts
  src/utils/formatDate.ts
Labels: ✨ Feature

#44 [#43] Rename: parsingJson 파일명 앞의 공백 삭제
  src/utils/parsingJson.ts
Labels: 🏷️ Rename

#46 [#45] Rename: 바뀐 파일명으로 import
  src/apis/thread/queryKey.ts
Labels: 🏷️ Rename

#47 [#5] Feat: 각 페이지와 스레드에 사용될 textArea 구현 및 예시 코드
  src/App.tsx
  src/apis/comment/queryFn.ts
  src/apis/comment/useCommentMutate.ts
  src/apis/notification/queryFn.ts
  src/apis/notification/useNotificationMutate.ts
  src/apis/thread/queryFn.ts
  src/apis/thread/useThreadMutate.ts
  src/components/Demo/ExMentionInput.tsx
  src/components/common/EditorTextArea.tsx
  src/components/common/Mention/AutoCompleteMentionList.tsx
  src/components/common/Mention/MentionInput.tsx
  src/components/common/Mention/UserBadgeList.tsx
  src/constants/anonymousNickName.ts
  src/hooks/api/useUploadComment.ts
  src/hooks/api/useUploadThread.ts
  src/hooks/useParentWidth.ts
Labels: ✨ Feature

#53 Hotfix: Common -> common git 설절변경
  src/components/common/LikeToggleButton.tsx
Labels: 🏷️ Rename

#37 [#16] Feat: 회원가입 로직 구현
  src/apis/auth/queryFn.ts
  src/apis/auth/useLogin.ts
  src/apis/auth/useRegister.ts
  src/components/Layout/Modals/Base/form.tsx
  src/components/Layout/Modals/Login/index.tsx
  src/components/Layout/Modals/Register/config.ts
  src/components/Layout/Modals/Register/index.tsx
  src/components/common/Mention/MentionInput.tsx
  src/components/common/Mention/UserBadgeList.tsx
Labels: ✨ Feature

#50 [#25] Feat: 내가 쓴 글 로직 구현
  src/apis/mythreads/queryFn.ts
  src/apis/mythreads/useMyThreadQuery.ts
  src/components/MyThreads/.empty
  src/components/MyThreads/MyComment.tsx
  src/components/MyThreads/MyPost.tsx
  src/components/MyThreads/MyThreadBody.tsx
  src/components/MyThreads/MyThreadDescription.tsx
  src/components/MyThreads/MyThreadItem.tsx
  src/components/MyThreads/ThreadBody.tsx
  src/components/MyThreads/ThreadItem.tsx
  src/pages/MyThreads/index.tsx
  src/types/channel.ts
Labels: ✨ Feature

#55 [#36] Feat: 로그인 후 새로고침 했을 때 유저 정보 다시 불러오는 로직 구현
  src/App.tsx
  src/apis/auth/queryFn.ts
  src/apis/auth/queryKey.ts
  src/apis/auth/useGetUserInfo.ts
  src/main.tsx
Labels: ✨ Feature

#59 [#58] Fix: lint-staged 설정 문제 해결
  package.json
Labels: ⚙ Chore, 🐞 Bugfix

#57 [#54] Feat: 내 알림 더미데이터 및 UI 구현
  src/components/MyNotifications/.empty
  src/components/MyNotifications/DUMMYNOTIFICATION.ts
  src/components/MyNotifications/DummyContent.tsx
  src/components/MyNotifications/MyNotificationBody.tsx
  src/components/MyNotifications/MyNotificationItem.tsx
  src/components/MyNotifications/MyNotificationTitle.tsx
  src/pages/MyNotifications/index.tsx
Labels: 🎨 Style

#56 [#38] Feat: 리스트 toolbar UI 구현
  src/components/Demo/ExToolbar.tsx
  src/components/Home/ThreadList.tsx
  src/components/common/thread/ThreadListItem.tsx
  src/components/common/thread/ThreadToolbar.tsx
  src/components/common/thread/ThreadTooltip.tsx
  src/hooks/api/useThreadsByChannel.ts
Labels: ✨ Feature

#62 [#61] Fix: 회원가입 시 로그인 모달 버벅임 버그 해결
  src/components/Layout/Modals/Register/index.tsx
Labels: 🐞 Bugfix

#64 [#63] Feat: 로그인 후 모달 닫기
  src/apis/auth/useLogin.ts
  src/components/Layout/Modals/Login/index.tsx
Labels: ✨ Feature

#66 [#65] Modify: 내가 쓴 글에서 커스텀훅으로 user정보 받아오도록 로직 변경
  src/components/MyThreads/MyThreadBody.tsx
Labels: ✏️ Modify

#67 [#60] Feat: 스레드 작성 form을 홈 페이지에 적용하기
  src/apis/auth/queryKey.ts
  src/apis/auth/useGetUserInfo.ts
  src/apis/thread/useGetThreads.ts
  src/apis/thread/usePostThread.ts
  src/apis/thread/usePutThread.ts
  src/apis/thread/useThreadMutate.ts
  src/components/Home/ThreadList.tsx
  src/components/common/EditorTextArea.tsx
  src/components/common/thread/ThreadListItem.tsx
  src/hooks/api/useThreadsByChannel.ts
  src/hooks/api/useUploadComment.ts
  src/hooks/api/useUploadThread.ts
  src/pages/Home/index.tsx
  src/types/thread.ts
  src/utils/parsingJson.ts
Labels: ✨ Feature

#69 [#68] Fix: getUserInfo 수정에 따른 내가 쓴 글 받아오기 변수 및 로직 변경
  src/apis/auth/queryKey.ts
  src/components/MyThreads/MyThreadBody.tsx
  src/components/common/thread/ThreadListItem.tsx
Labels: 🐞 Bugfix

#70 [#48] feature : textArea에 맨션기능 추가
  src/App.tsx
  src/apis/comment/usePostComment.ts
  src/apis/notification/usePostNotification.ts
  src/components/Demo.tsx
  src/components/common/EditorTextArea.tsx
  src/components/common/Mention/AutoCompleteMentionList.tsx
  src/components/common/Mention/MentionInput.tsx
  src/constants/anonymousNickname.ts
  src/hooks/api/useUploadComment.ts
  src/hooks/api/useUploadThread.ts
Labels: ✨ Feature, 🐞 Bugfix

#74 Cleanup: demo 삭제
  src/App.tsx
  src/components/Demo/ExEditerTextArea.tsx
Labels: 🗑️ Cleanup

#78 [#76] Feat: EditerTextArea에 멘션기능, 알림기능 추가
  src/App.tsx
  src/apis/comment/queryFn.ts
  src/apis/comment/useDeleteComment.ts
  src/apis/mention/queryFn.ts
  src/apis/mention/usePostMention.ts
  src/apis/thread/queryFn.ts
  src/apis/thread/queryKey.ts
  src/apis/thread/useDeleteThread.ts
  src/apis/thread/useGetThread.ts
  src/apis/thread/usePutThread.ts
  src/components/Demo/ExEditerTextArea.tsx
  src/components/Demo/ExEditorTextArea.tsx
  src/components/Demo/ExToolbar.tsx
  src/components/Home/ThreadList.tsx
  src/components/common/EditorTextArea.tsx
  src/components/common/mention/AutoCompleteMentionList.tsx
  src/components/common/mention/MentionInput.tsx
  src/components/common/mention/UserBadgeList.tsx
  src/components/common/thread/ThreadListItem.tsx
  src/components/common/thread/ThreadToolbar.tsx
  src/constants/dummyData.ts
  src/hooks/api/useChangeThread.ts
  src/hooks/api/useCreateThread.ts
  src/hooks/api/useEditorLogicByProps.ts
  src/hooks/api/useMentionNotification.ts
  src/hooks/api/useUploadComment.ts
  src/hooks/api/useUploadThread.ts
  src/hooks/api/useUserListByDB.ts
  src/hooks/useParentWidth.ts
  src/lib/editorContent.ts
  src/pages/Home/index.tsx
Labels: ✨ Feature

#85 Fix: comment 알림의 대상, 멘션 타입 수정
  src/components/Demo/ExEditorTextArea.tsx
  src/hooks/api/useEditorLogicByProps.ts
  src/hooks/api/useMentionNotification.ts
  src/hooks/api/useUploadComment.ts
Labels: 🐞 Bugfix

#79 [#72] Style: 프로필 편집 모달 UI 퍼블리싱
  src/components/Layout/Modals/Base/form.tsx
  src/components/Layout/Modals/Base/modal.tsx
  src/components/Layout/Modals/Setting/ImageUploadForm.tsx
  src/components/Layout/Modals/Setting/config.ts
  src/components/Layout/Modals/Setting/index.tsx
  src/components/Layout/Sidebar/ThemeConfigDropdown.tsx
Labels: 🎨 Style

#80 [#73] Modify: zustand user 스토어 걷어내고 modal 스토어 생성
  src/apis/auth/useLogin.ts
  src/stores/modal.ts
  src/stores/user.ts
Labels: ✏️ Modify

#86 [#83] Feat: 내 알림 api 연동 및 로직구현
  src/apis/mynotification/queryFn.ts
  src/apis/mynotification/queryKey.ts
  src/apis/mynotification/useGetMentioned.ts
  src/apis/mynotification/useGetNotification.ts
  src/apis/thread/queryFn.ts
  src/components/MyNotifications/CommentNotification.tsx
  src/components/MyNotifications/DUMMYNOTIFICATION.ts
  src/components/MyNotifications/DummyContent.tsx
  src/components/MyNotifications/MentionNotification.tsx
  src/components/MyNotifications/MyNotificationBody.tsx
  src/components/MyNotifications/MyNotificationItem.tsx
  src/hooks/api/useListedNotificationAndMention.ts
  src/types/notification.ts
Labels: ✨ Feature

#90 [#89] Feat: 로그아웃 기능 구현
  src/apis/auth/queryFn.ts
  src/apis/auth/usePostLogout.ts
  src/components/Layout/Sidebar/view.tsx
  src/utils/localStorage.ts
Labels: ✨ Feature

#91 [#52] Feat: 툴바의 좋아요 버튼 클릭시, 좋아요 요청과 좋아요 삭제 요청 구현
  src/apis/channel/useGetChannel.ts
  src/apis/channel/useGetChannelDetails.ts
  src/apis/thread/queryFn.ts
  src/apis/thread/useDeleteThreadLike.ts
  src/apis/thread/usePostThreadLike.ts
  src/components/Home/ChannelNavigationMenu.tsx
  src/components/Home/ThreadList.tsx
  src/components/common/thread/ThreadListItem.tsx
  src/components/common/thread/ThreadToolbar.tsx
  src/components/common/thread/ThreadTooltip.tsx
  src/hooks/api/useThreadsByChannel.ts
  src/pages/Home/index.tsx
  src/types/thread.ts
  src/utils/parsingJson.ts
Labels: ✨ Feature

#93 [#33] Feat: 스레드 자세히 보기
  src/App.tsx
  src/components/Demo/ExThreadDetailView.tsx
  src/components/common/thread/CommentListItem.tsx
  src/components/common/thread/ThreadDetailView.tsx
Labels: ✨ Feature

#97 [#82] Feat: 내가 쓴 글 게시판에 댓글 출력 구현
  src/apis/mythreads/queryFn.ts
  src/apis/mythreads/queryKey.ts
  src/apis/mythreads/useGetMyComments.ts
  src/apis/mythreads/useGetMyThread.ts
  src/components/MyThreads/MyComment.tsx
  src/components/MyThreads/MyPost.tsx
  src/components/MyThreads/MyThreadBody.tsx
  src/components/MyThreads/MyThreadItem.tsx
  src/hooks/api/useListedNotificationAndMention.ts
  src/hooks/api/useListedThreadsAndComments.ts
  src/types/user.ts
Labels: ✨ Feature

#94 [#81] Feat: 프로필 변경 로직 구현
  src/apis/auth/queryFn.ts
  src/apis/auth/usePutProfile.ts
  src/components/Layout/Modals/Base/form.tsx
  src/components/Layout/Modals/Base/modal.tsx
  src/components/Layout/Modals/Setting/config.ts
  src/components/Layout/Modals/Setting/index.tsx
Labels: ✨ Feature

#96 [#87] Feat: 좋아요 알림 api와 커스텀 훅 구현 및 적용
  package.json
  src/apis/thread/queryFn.ts
  src/apis/thread/usePostThreadLike.ts
  src/components/common/thread/ThreadListItem.tsx
  src/constants/notification.ts
  src/hooks/api/useLikeThread.ts
  src/hooks/api/useMentionNotification.ts
  src/hooks/api/useUploadComment.ts
  src/pages/Home/index.tsx
  yarn.lock
Labels: ✨ Feature

#99 [#88] feat:회원가입 시 임시DB에 userId 변경하기
  src/App.tsx
  src/apis/auth/queryFn.ts
  src/components/Demo/ExEditorTextArea.tsx
  src/components/Layout/Modals/Register/index.tsx
  src/hooks/api/useUpdateUserList.ts
  src/hooks/api/useUserListByDB.ts
Labels: ✨ Feature

#103 [#101] Fix: 내 알림에 아무것도 없을 시 에러처리
  src/components/MyNotifications/LikeNotification.tsx
  src/components/MyNotifications/MyNotificationBody.tsx
  src/components/MyNotifications/MyNotificationItem.tsx
  src/types/notification.ts
  src/types/thread.ts
Labels: 🐞 Bugfix

#109 [#41] Feat: 회원가입, 로그인 모달에서 에러 경고, 혹은 성공 토스트 메시지 처리
  src/App.tsx
  src/apis/auth/useLogin.ts
  src/apis/auth/usePostLogin.ts
  src/components/Layout/Modals/Login/index.tsx
  src/components/Layout/Modals/Register/index.tsx
  src/constants/authError.ts
  src/hooks/api/useUpdateUserList.ts
Labels: ✨ Feature

#107 [#106] Feat: 내가 쓴 글 클릭 시 스레드 아이템 출력
  src/apis/thread/queryFn.ts
  src/apis/thread/useDeleteThreadLike.ts
  src/apis/thread/usePostThreadLike.ts
  src/components/MyNotifications/MyNotificationItem.tsx
  src/components/MyThreads/MyThreadBody.tsx
  src/components/MyThreads/MyThreadItem.tsx
  src/components/common/thread/CommentListItem.tsx
  src/components/common/thread/ThreadDetailView.tsx
  src/components/common/thread/ThreadListItem.tsx
  src/pages/Home/index.tsx
  src/pages/MyNotifications/index.tsx
  src/pages/MyThreads/index.tsx
  src/stores/thread.ts
Labels: ✨ Feature

#113 [#108] Feat: 내 알림, 내가 쓴 글이 비어있을 시 디폴트 내용 출력
  src/components/MyNotifications/MyNotificationBody.tsx
  src/components/MyNotifications/MyNotificationItem.tsx
  src/components/MyThreads/MyThreadBody.tsx
  src/components/common/myactivate/emptyThread.tsx
Labels: ✨ Feature

#115 [#111] Fix: 댓글 추가시 invalidate 및 스레드 상세보기 댓글 에디터 추가
  src/apis/comment/usePostComment.ts
  src/apis/thread/queryFn.ts
  src/apis/thread/useDeleteThreadLike.ts
  src/apis/thread/usePostThreadLike.ts
  src/components/Demo/ExThreadDetailView.tsx
  src/components/Home/ThreadList.tsx
  src/components/MyThreads/MyComment.tsx
  src/components/MyThreads/MyThreadBody.tsx
  src/components/common/LikeToggleButton.tsx
  src/components/common/thread/CommentListItem.tsx
  src/components/common/thread/ThreadDetailView.tsx
  src/components/common/thread/ThreadListItem.tsx
  src/components/common/thread/ThreadToolbar.tsx
  src/pages/Home/index.tsx
  src/pages/MyNotifications/index.tsx
  src/pages/MyThreads/index.tsx
  src/utils/parsingJson.ts
Labels: 🐞 Bugfix

#114 [#110] Feat: 프로필 편집 시 성공/에러 토스트 메시지 처리
  src/apis/auth/usePutProfile.ts
  src/components/Layout/Modals/Login/index.tsx
  src/components/Layout/Modals/Register/index.tsx
  src/components/Layout/Modals/Setting/config.ts
  src/components/Layout/Modals/Setting/index.tsx
  src/constants/toastMessage.ts
Labels: ✨ Feature

#120 [#119] Fix: 내 알림 멘션이 본인에게 오는 오류
  src/apis/mynotification/useGetMentioned.ts
  src/components/MyNotifications/MyNotificationBody.tsx
  src/components/MyThreads/MyThreadBody.tsx
  src/components/common/myactivate/EmptyThread.tsx
  src/hooks/api/useListedNotificationAndMention.ts
Labels: 🐞 Bugfix

#117 [#116] Feat: 닉네임 유효성 검사, 스타일, 사이드바 아이콘 변경 및 QA 이슈 수정
  src/components/Layout/Modals/Base/form.tsx
  src/components/Layout/Modals/Base/modal.tsx
  src/components/Layout/Modals/Profile/ImageUploadForm.tsx
  src/components/Layout/Modals/Profile/config.ts
  src/components/Layout/Modals/Profile/index.tsx
  src/components/Layout/Modals/Register/config.ts
  src/components/Layout/Sidebar/config.ts
  src/components/Layout/Sidebar/view.tsx
  src/components/common/EditorTextArea.tsx
  src/stores/modal.ts
Labels: ✏️ Modify

#125 [#122] Feat: 로그인/로그아웃 토스트 메시지 띄우기
  src/components/Layout/Sidebar/view.tsx
Labels: ✨ Feature

#130 [#128] Refactor: 사이드바 button 태그로 이루어진 아이콘 컴포넌트화
  src/components/Layout/Sidebar/SidebarButton.tsx
  src/components/Layout/Sidebar/view.tsx
Labels: 🔨 Refactor

#133 [#132] Feat: open graph 적용
  index.html
  public/favicon.png
  public/og_thumbnail.png
Labels: ✨ Feature

#124 [#118] Feat: use toast hook 구현 및 좋아요 클릭시 토스트 적용
  src/components/common/thread/ThreadListItem.tsx
  src/components/common/thread/ThreadToolbar.tsx
  src/hooks/common/useToast.ts
Labels: ✨ Feature

#129 [#126] Feat: 멘션된 유저 리스트 Thread에 띄우기
  src/apis/thread/queryFn.ts
  src/components/MyNotifications/MyNotificationBody.tsx
  src/components/common/EditorTextArea.tsx
  src/components/common/mention/AutoCompleteMentionList.tsx
  src/components/common/mention/MentionInput.tsx
  src/components/common/thread/CommentListItem.tsx
  src/components/common/thread/ThreadListItem.tsx
  src/constants/dummyData.ts
  src/hooks/api/useChangeThread.ts
  src/hooks/api/useCreateThread.ts
  src/hooks/api/useEditorLogicByProps.ts
  src/hooks/api/useMentionNotification.ts
  src/hooks/api/useUploadComment.ts
  src/lib/editorContent.ts
  src/types/thread.ts
  src/utils/parsingJson.ts
Labels: ✨ Feature

#145 [#143] Feat: 기존 스레드 수정 시 EditorTextArea 띄우면 x 버튼으로 추가
  src/components/common/EditorTextArea.tsx
  src/pages/Home/index.tsx
Labels: ✨ Feature

#140 [#137] Refactor: toast 메시지 커스텀훅으로 변경
  src/components/Layout/Modals/Login/index.tsx
  src/components/Layout/Modals/Profile/index.tsx
  src/components/Layout/Modals/Register/index.tsx
  src/components/Layout/Sidebar/view.tsx
  src/constants/toastMessage.ts
  src/hooks/common/useToast.ts
Labels: 🔨 Refactor

#144 [#141] Feat: 에디터에서 엔터시 submit 되도록 구현
  src/components/Home/ThreadList.tsx
  src/components/common/EditorTextArea.tsx
  src/components/common/thread/ThreadListItem.tsx
  src/pages/Home/index.tsx
Labels: ✨ Feature

#146 [#138] Style: 내 알림, 내가 작성한 글 페이지에 비어있는 경우 "텅" 글자가 가운데 오도록 스타일 변경
  src/components/MyNotifications/MyNotificationBody.tsx
  src/components/MyThreads/MyThreadBody.tsx
Labels: 🎨 Style

#142 [#139] Fix: 댓글에서 익명 해제시 모달창 오픈 버그 해결
  src/components/Layout/Modals/Profile/config.ts
  src/components/Layout/Modals/Register/config.ts
  src/components/Layout/Modals/Register/index.tsx
  src/components/common/EditorTextArea.tsx
  src/components/common/mention/AutoCompleteMentionList.tsx
  src/constants/commonConstants.ts
  src/lib/editorContent.ts
Labels: 🐞 Bugfix

#149 [#148] Fix:긴 글 작성 시 스레드 자세히 보기 사이즈가 변경 됨
  src/components/common/EditorTextArea.tsx
  src/components/common/thread/ThreadDetailView.tsx
Labels: 🐞 Bugfix

#131 [#121] Feat 사이드바 알림 실제 api 연동
  src/apis/mynotification/queryFn.ts
  src/components/Layout/Sidebar/index.tsx
  src/components/Layout/Sidebar/view.tsx
  src/pages/MyNotifications/index.tsx
  src/stores/notificaitons.ts
Labels: ✨ Feature

#151 [#147] Modify: 모달 뒷 배경 닫힘 처리, auto focus 문제 QA 반영
  src/components/Layout/Modals/Base/form.tsx
  src/components/Layout/Modals/Base/modal.tsx
  src/components/Layout/Modals/Login/config.ts
  src/components/Layout/Modals/Profile/config.ts
  src/components/Layout/Modals/Register/config.ts
Labels: 🐞 Bugfix, ✏️ Modify

#153 [#152] Fix: 회원가입 이름 placeholder 문구 변경
  src/components/Layout/Modals/Register/config.ts
Labels: 🐞 Bugfix

#155 [154] Fix: 삭제된 댓글에 대하여 파싱에러 해결
  src/components/Layout/Sidebar/index.tsx
  src/components/MyNotifications/CommentNotification.tsx
Labels: 🐞 Bugfix

#150 [#127] Feat: 편집 버튼 클릭시 에디터로 변환
  src/apis/comment/useDeleteComment.ts
  src/apis/thread/usePutThread.ts
  src/components/common/EditorTextArea.tsx
  src/components/common/thread/CommentListItem.tsx
  src/components/common/thread/ThreadDetailView.tsx
  src/components/common/thread/ThreadListItem.tsx
  src/components/common/thread/ThreadToolbar.tsx
  src/hooks/api/useChangeThread.ts
  src/hooks/api/useEditorLogicByProps.ts
  src/hooks/api/useUpdateUserList.ts
Labels: ✨ Feature

#134 [#123] Feat: Sentry 연동
  .gitignore
  package.json
  src/components/Layout/Modals/Login/index.tsx
  src/components/Layout/Modals/Profile/index.tsx
  src/components/Layout/Modals/Register/index.tsx
  src/components/Layout/Sidebar/ThemeConfigDropdown.tsx
  src/components/Layout/Sidebar/view.tsx
  src/components/Layout/index.tsx
  src/components/common/EditorTextArea.tsx
  src/components/common/mention/MentionInput.tsx
  src/components/common/thread/ThreadListItem.tsx
  src/hooks/api/useEditorLogicByProps.ts
  src/main.tsx
  src/pages/Error/index.tsx
  src/pages/Home/index.tsx
  src/pages/MyNotifications/index.tsx
  src/pages/MyThreads/index.tsx
  src/pages/NotFound/index.tsx
  vite.config.ts
  yarn.lock
Labels: ✨ Feature

#157 Feat: 개선 사항 게시판 탭 추가
  src/components/Home/ChannelNavigationMenu.tsx
Labels: ✨ Feature

#160 [#159] Fix: 댓글 작성시 스레드에 '편집중' 추가는 이슈
  src/components/common/thread/ThreadListItem.tsx
Labels: 🐞 Bugfix

#162 [#161] Feat: 내가 쓴 글 및 알람 건의 게시판 매핑
  src/components/MyNotifications/MyNotificationItem.tsx
  src/components/MyThreads/MyThreadItem.tsx
Labels: 🐞 Bugfix

#164 [#163] Sentry에서 react-query 오류도 보고되게 변경
  src/apis/comment/useDeleteComment.ts
  src/apis/comment/usePostComment.ts
  src/apis/mention/usePostMention.ts
  src/apis/notification/usePostNotification.ts
  src/apis/thread/useDeleteThread.ts
  src/apis/thread/usePostThread.ts
  src/apis/thread/usePostThreadLike.ts
  src/apis/thread/usePutThread.ts
  src/components/Layout/Modals/Login/index.tsx
  src/components/Layout/Modals/Profile/index.tsx
  src/components/Layout/Modals/Register/index.tsx
  src/components/Layout/Sidebar/ThemeConfigDropdown.tsx
  src/components/Layout/Sidebar/view.tsx
  src/components/common/EditorTextArea.tsx
  src/components/common/mention/MentionInput.tsx
  src/components/common/thread/ThreadListItem.tsx
  src/main.tsx
  src/pages/Error/index.tsx
  src/pages/Home/index.tsx
  src/pages/MyNotifications/index.tsx
  src/pages/MyThreads/index.tsx
  src/pages/NotFound/index.tsx
  src/utils/localStorage.ts
  src/utils/logger.ts
  src/utils/parsingJson.ts
Labels: ✨ Feature

#167 [#166] Feat: 사이드바 프로필에 닉네임 반영
  src/components/Layout/Sidebar/index.tsx
Labels: ✨ Feature

#175 [#170] Fix: 스레드 상세보기에서 말줄임 제거
  src/components/common/thread/ThreadDetailView.tsx
  src/components/common/thread/ThreadListItem.tsx
Labels: 🐞 Bugfix

#172 [#171] Fix: 익명 체크여부 기본값 수정
  src/components/common/EditorTextArea.tsx
  src/components/common/thread/ThreadListItem.tsx
Labels: 🐞 Bugfix

#193 [#181] Feat: 잡담 게시판 추가
  src/components/Home/ChannelNavigationMenu.tsx
Labels: ✨ Feature

#177 [#176] Feat: 다크 모드 색상 팔레트 및 전환 기능 도입
  public/background-gradient.css
  src/components/Home/ChannelNavigationMenu.tsx
  src/components/Layout/Modals/Base/form.tsx
  src/components/Layout/Modals/Base/modal.tsx
  src/components/Layout/Sidebar/ThemeConfigDropdown.tsx
  src/components/Layout/Sidebar/styles.ts
  src/components/Layout/Sidebar/view.tsx
  src/components/Layout/index.tsx
  src/components/MyNotifications/MyNotificationItem.tsx
  src/components/MyNotifications/MyNotificationTitle.tsx
  src/components/MyThreads/MyComment.tsx
  src/components/MyThreads/MyPost.tsx
  src/components/MyThreads/MyThreadDescription.tsx
  src/components/MyThreads/MyThreadItem.tsx
  src/components/common/EditorTextArea.tsx
  src/components/common/LikeToggleButton.tsx
  src/components/common/mention/AutoCompleteMentionList.tsx
  src/components/common/mention/MentionInput.tsx
  src/components/common/mention/UserBadgeList.tsx
  src/components/common/thread/CommentListItem.tsx
  src/components/common/thread/ThreadDetailView.tsx
  src/components/common/thread/ThreadListItem.tsx
  src/components/common/thread/ThreadToolbar.tsx
  src/components/common/thread/ThreadTooltip.tsx
  src/components/ui/input.tsx
  src/components/ui/separator.tsx
  src/components/ui/textarea.tsx
  src/index.css
  src/main.tsx
  src/pages/Home/index.tsx
  src/pages/MyNotifications/index.tsx
  src/pages/MyThreads/index.tsx
  tailwind.config.js
Labels: ✨ Feature

#184 [#98] Feat: 프로필 사진 변경 기능 구현
  src/apis/auth/queryFn.ts
  src/apis/auth/usePutProfile.ts
  src/components/Layout/Modals/Profile/ImageUploadForm.tsx
  src/components/Layout/Modals/Profile/index.tsx
  src/components/common/thread/CommentListItem.tsx
  src/components/common/thread/ThreadDetailView.tsx
  src/components/common/thread/ThreadListItem.tsx
  src/constants/commonConstants.ts
  src/constants/toastMessage.ts
Labels: ✨ Feature

#180 [#179] Feat: 좋아요, 좋아요 삭제 api에 낙관적 업데이트 적용 및 수정
  src/apis/thread/useDeleteThread.ts
  src/apis/thread/useDeleteThreadLike.ts
  src/apis/thread/useGetThread.ts
  src/apis/thread/useGetThreads.ts
  src/apis/thread/usePostThreadLike.ts
  src/components/common/thread/ThreadListItem.tsx
  src/hooks/api/useLikeThread.ts
  src/hooks/api/useToggleLike.ts
  src/hooks/common/useIntersectionObserver.ts
Labels: ✨ Feature, 🐞 Bugfix

#185 [#182] Feat: 스켈레톤 로딩 구현
  src/components/MyNotifications/MyNotificationBody.tsx
  src/components/MyNotifications/MyNotificationItem.tsx
  src/components/MyNotifications/MyNotificationTitle.tsx
  src/components/MyThreads/MyComment.tsx
  src/components/MyThreads/MyPost.tsx
  src/components/MyThreads/MyThreadBody.tsx
  src/components/MyThreads/MyThreadItem.tsx
  src/components/Skelton/CommentListItemSkeleton.tsx
  src/components/Skelton/MyThreadSkeleton.tsx
  src/components/Skelton/ThreaDetailItemSkeleton.tsx
  src/components/Skelton/ThreadDetailSkeleton.tsx
  src/components/Skelton/ThreadListItemSkelton.tsx
  src/components/Skelton/ThreadListSkeleton.tsx
  src/pages/Home/index.tsx
Labels: ✨ Feature

#187 [#186] Refactor: 모달 useOverlay 사용하여 전역에서 관리
  package.json
  src/apis/auth/usePostLogin.ts
  src/apis/auth/usePostLogout.ts
  src/components/Layout/Modals/Login/index.tsx
  src/components/Layout/Modals/Profile/index.tsx
  src/components/Layout/Modals/Register/index.tsx
  src/components/Layout/Sidebar/view.tsx
  src/components/common/EditorTextArea.tsx
  src/components/common/thread/ThreadListItem.tsx
  src/hooks/api/useUpdateUserList.ts
  src/main.tsx
  src/stores/modal.ts
  yarn.lock
Labels: 🔨 Refactor

#189 [#188] Modify: 로그인/자동 로그인 토스트 메시지 분리
  src/apis/auth/usePostLogout.ts
  src/components/Layout/Sidebar/view.tsx
Labels: ✏️ Modify

#198 [#197] Feat: Google Analytics 4 연동
  package.json
  vite.config.ts
  yarn.lock
Labels: ✨ Feature

#191 [#190] Feat: 이용 방법 모달 생성
  src/components/Layout/Modals/Information/index.tsx
  src/components/Layout/Sidebar/view.tsx
  src/components/Layout/index.tsx
  src/constants/commonConstants.ts
Labels: ✨ Feature

#192 [#168] Feat: 무한 스크롤 훅 구현 및 적용
  src/apis/channel/useGetChannelDetails.ts
  src/apis/thread/queryFn.ts
  src/apis/thread/queryKey.ts
  src/apis/thread/useGetThreads.ts
  src/components/Home/ThreadList.tsx
  src/components/common/thread/ThreadDetailView.tsx
  src/components/common/thread/ThreadListItem.tsx
  src/hooks/api/useThreadsByChannel.ts
  src/pages/Home/index.tsx
Labels: ✨ Feature

#199 [#196] Modify: 날짜 포맷팅 함수 변경
  package.json
  src/components/MyNotifications/CommentNotification.tsx
  src/components/MyNotifications/LikeNotification.tsx
  src/components/MyNotifications/MentionNotification.tsx
  src/components/MyThreads/MyThreadItem.tsx
  src/utils/formatDateFns.ts
  yarn.lock
Labels: ✏️ Modify

#200 [#195] Feat: 스레드 리스트, 스레드 상세보기 스켈레톤 적용
  src/components/Skelton/ThreadDetailSkeleton.tsx
  src/components/common/myactivate/EmptyThread.tsx
  src/components/common/thread/ThreadDetailView.tsx
  src/hooks/api/useThreadsByChannel.ts
  src/pages/Home/index.tsx
Labels: ✨ Feature

#194 [#183] Feat: 슬랙API를 이용해서 슬랙 봇 연동 및 알림 보내기
  .gitignore
  src/apis/auth/usePostRegister.ts
  src/apis/slackBot/queryFn.ts
  src/apis/slackBot/usePostSlackMessage.ts
  src/components/Layout/Modals/Register/index.tsx
  src/components/common/mention/AutoCompleteMentionList.tsx
  src/components/common/mention/UserBadgeList.tsx
  src/constants/toastMessage.ts
  src/hooks/api/useChangeThread.ts
  src/hooks/api/useCreateThread.ts
  src/hooks/api/useMentionNotification.ts
  src/hooks/api/useRegister.ts
  src/hooks/api/useUpdateUserList.ts
  src/hooks/api/useUploadComment.ts
  src/hooks/api/useUserListByDB.ts
Labels: ✨ Feature

#211 [#210 ] Fix: 멘션 자동완성 클릭이벤트 미동작 에러
  src/components/common/mention/AutoCompleteMentionList.tsx
  src/components/common/mention/MentionInput.tsx
  src/components/common/mention/UserBadgeList.tsx
Labels: 🐞 Bugfix

#213 [#212] 무한스크롤 머지 이후 배포환경 정상작동 안하는 이슈
  src/apis/thread/queryFn.ts
  src/apis/thread/queryKey.ts
  src/apis/thread/useGetThreads.ts
  src/components/Home/ThreadList.tsx
  src/hooks/api/useThreadsByChannel.ts
  src/pages/Home/index.tsx
Labels: 🐞 Bugfix, ✏️ Modify

#208 [#201] Fix: 댓글 추가, 삭제시 리스트 query key invalidate
  src/apis/comment/useDeleteComment.ts
  src/apis/comment/usePostComment.ts
  src/components/common/EditorTextArea.tsx
  src/components/common/thread/ThreadDetailView.tsx
  src/hooks/api/useEditorLogicByProps.ts
  src/hooks/api/useUploadComment.ts
Labels: 🐞 Bugfix

#203 [#202] Refactor: Sentry -> GA4 로그 수집 위치 변경
  package.json
  src/components/Layout/Modals/Login/index.tsx
  src/components/Layout/Modals/Profile/ImageUploadForm.tsx
  src/components/Layout/Modals/Profile/index.tsx
  src/components/Layout/Modals/Register/index.tsx
  src/components/Layout/Sidebar/ThemeConfigDropdown.tsx
  src/components/Layout/Sidebar/view.tsx
  src/components/common/EditorTextArea.tsx
  src/components/common/mention/MentionInput.tsx
  src/components/common/thread/ThreadListItem.tsx
  src/hooks/api/useToggleLike.ts
  src/pages/Error/index.tsx
  src/pages/MyNotifications/index.tsx
  src/pages/MyThreads/index.tsx
  src/pages/NotFound/index.tsx
  vite.config.ts
  yarn.lock
Labels: ✨ Feature

#205 [#204] Chore: open graph - sitename 추가
  index.html
Labels: ⚙ Chore

#214 [#209] Fix: 좋아요 반영 안되는 문제 해결 및 무한 스크롤 이슈 해결
  src/apis/thread/queryFn.ts
  src/apis/thread/queryKey.ts
  src/apis/thread/useDeleteThreadLike.ts
  src/apis/thread/useGetThreads.ts
  src/apis/thread/usePostThreadLike.ts
  src/components/Home/ThreadList.tsx
  src/components/common/thread/CommentListItem.tsx
  src/components/common/thread/ThreadDetailView.tsx
  src/components/common/thread/ThreadListItem.tsx
  src/hooks/api/useThreadsByChannel.ts
  src/pages/Home/index.tsx
Labels: 🐞 Bugfix

#216 [#215] Fix: GA4 script를 개발 환경에서는 로딩하지 않는 오류
  vite.config.ts
Labels: 🐞 Bugfix

#219 [#217] Style: 라이트 테마 배경색의 밝기 높이기
  src/index.css
Labels: 🎨 Style

#220 [#218] Fix: 로그인, 내 정보 수정 모달 수정
  src/apis/auth/usePostLogout.ts
  src/apis/thread/useGetThreads.ts
  src/components/Layout/Modals/Information/index.tsx
  src/components/Layout/Modals/Login/index.tsx
  src/components/Layout/Modals/Profile/index.tsx
  src/components/Layout/Sidebar/view.tsx
Labels: 🐞 Bugfix

#224 [#223] Fix: 유저정보 업데이트 실패시 에러처리
  .gitignore
  src/hooks/api/useUpdateUserList.ts
Labels: 🐞 Bugfix

#222 [#221] Feat: 내가 쓴 글, 내 알림 채널 매핑
  src/components/MyNotifications/MyNotificationItem.tsx
  src/components/MyThreads/MyThreadItem.tsx
  src/components/common/thread/ThreadDetailView.tsx
  src/types/channel.ts
Labels: ✨ Feature

#227 [#226] Fix: 댓글 추가, 삭제시 ui 반영 속도 개선
  src/apis/comment/useDeleteComment.ts
  src/apis/comment/usePostComment.ts
  src/components/common/thread/CommentListItem.tsx
  src/components/common/thread/ThreadListItem.tsx
  src/hooks/common/useToast.ts
Labels: 🐞 Bugfix

#231 [#230] Style: 스레드 리스트, 상세보기 요청 실패시 보이는 에러 컴포넌트 구현 및 적용
  src/apis/thread/useGetThreads.ts
  src/components/Error/ApiError.tsx
  src/components/common/thread/ThreadDetailView.tsx
  src/hooks/api/useThreadsByChannel.ts
  src/pages/Home/index.tsx
Labels: 🎨 Style

#229 [#228] Fix: 스레드 작성 및 삭제시 UI 즉시 업데이트
  src/apis/thread/useDeleteThread.ts
  src/apis/thread/usePostThread.ts
Labels: 🐞 Bugfix
